apiVersion: v1
kind: Service
metadata:
  name: hw2-service
spec:
  selector:
    app: crud-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
