POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "test-user",
  "firstName": "Test",
  "lastName": "User",
  "email": "test-user@test.com",
  "phone": "+380999012233"
}

###

POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "test-user2",
  "firstName": "Test",
  "lastName": "User",
  "email": "test-user2@test.com",
  "phone": "+380999012234"
}

###

PUT http://localhost:8080/user/1
Content-Type: application/json

{
  "lastName": "Updated"
}

###

GET http://localhost:8080/user

###

GET http://localhost:8080/user/1

###

DELETE http://localhost:8080/user/1