{
 "title": "Application Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Spring metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{uri=~\"/api/.*\"}[5m]))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "Latency 0.99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[5m])))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "Latency 0.95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[5m])))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "Latency 0.5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[5m])))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    },
    {
     "title": "Latency max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "max by (uri, method) (rate(http_server_requests_seconds_max{uri=~\"/api/.*\"}[5m]))",
       "legendFormat": "[{{method}}] {{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "nginx metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"app-service\"}[5m]))",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5..\", exported_service=\"app-service\"}[5m]))",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Latency 0.99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"app-service\"}[5m])))",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Latency 0.95",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"app-service\"}[5m])))",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "Latency 0.5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"app-service\"}[5m])))",
       "legendFormat": "all"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pod memory usage (mb)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (id) (label_replace(container_memory_usage_bytes{namespace=\"otus-lab\", container=\"service-chart\", id=~\"/docker/.*\"}, \"id\", \"$1\", \"id\", \".*/(pod.*)/.*\")/1024/1024)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Pod  CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{namespace=\"otus-lab\", container=\"service-chart\", id=~\"/docker/.*\"}[5m])) by (id), \"id\", \"$1\", \"id\", \".*/(pod.*)/.*\")",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}