CREATE TABLE "public"."user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "public"."user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "public"."user"
    ADD CONSTRAINT uc_user_phone UNIQUE (phone);

ALTER TABLE "public"."user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);