apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-app-config
data:
  {{ if .Values.postgresql.auth.username }}
  POSTGRES_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  {{ else }}
  POSTGRES_USERNAME: "postgres"
  {{ end }}
  POSTGRES_HOST: "hw3-service-postgresql"
  POSTGRES_PORT: "5432"
