apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-app-config
data:
  POSTGRES_USERNAME: {{ .Values.db.username | quote }}
  {{ if .Values.db.host }}
  POSTGRES_HOST: {{ .Values.db.host | quote }}
  {{ else }}
  POSTGRES_HOST: "postgres-lab-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
  {{ end }}
  POSTGRES_PORT: {{ .Values.db.port | quote }}
