apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-password: {{ required "Please specify .Values.global.postgresql.auth.postgresPassword" .Values.global.postgresql.auth.postgresPassword | b64enc }}
