apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: crud-app
spec:
  selector:
    app: crud-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: web
  type: {{ .Values.service.type }}
